@basepath = http://localhost:5135

GET {{basepath}}/

### Register a new user
POST {{basepath}}/account/register
Content-Type: application/json

{
  "username": "example@example.com",
  "password": "ExamplePassword123456!",
  "email": "example@example.com"
}

### Login and retrieve tokens and set accesstoken variable
POST {{basepath}}/account/login
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "ExamplePassword123456!"
}

### {
#   "tokenType": "Bearer",
#   "accessToken": "CfDJ8JQ6UejBIoRIkUpEJR_892d-zbl9LEcgWQiW6uF55wQzMaIo9tELg3ATO_91h3I6CFxA4uC6yNJGx2o3Mk3iSVzPF6iTZetbunzE-Yxf40apjpXEZkc_dEYMQfnpDIq8XJFclh8uWLTLk7Jq7Ne1Rg7LNK-Uh5vzqgP5bS609Viu8dV29kgtK1RfIU2N_7o4lw1X-YoX38jwyc-ArodRrJRkcMsEs0ts2L1pIRKQH8NO3x-fcmQLGJrcutKg9OBTlscx6r-WCc_bJMjGdDQgXrZEYu-XSPbgc4FAB3C3NAZFEqqwXW1NLIb_3Xa3CYqrsX2veomIXNgq3YoomZ0rMdm94gC7Z1R8LjMAWecPU9p2UB1IFIbvLMRLpmgIVHQjTaHKS42-uA0NB5TdJxaF0Gc90czUmd8PG9l5yEPgDPiQLztkk5vBm0y_HR5cgUDQdEwSQt8Av0gsmbME9atzkxeFFFTVezB52YR_SsMzbx5q_lJE-ux6SDdmykzbSwjg4ecJRPd6_G_MNMt72Pc-gTIHZC56zqyrUt_6N3RdsQTSt5_6dl42IGRMO6j6JRrk9BRpWykWLylDcLfNyfGx1QV7cyqbKIPNbOLFT2VKsA_Svz79Gb37VyiaNEppMjO2UI6CWj1DxazYWNMERiQ0Tfj1Q7HIJkFINC9fIbNPI2SjqNurAxCTIAfBqzf0Nox8hl1bcZN7OSun8-u7nhbqdg0",
#   "expiresIn": 3600,
#   "refreshToken": "CfDJ8JQ6UejBIoRIkUpEJR_892dg_5gvwNBXBMYLYQj05RIc14gg_31KrsnOjceSSvrowYNz_kXZ2g8jdWl91ctdU3A3yy5krWnD_p-sJAUNF_OT6NTsZrhnajn7bLOtjgGQ3tbaFYq5_qEGYFXkDk9N3leqQQnyXwoa7sfIVijq_-BjK1kcg9EoyUmlQQ17ysdtw4S5AFQ8b-K8CrVCIDuUYopb5cviYcXBMBkoGz2EkY2og67F1yEFpuMbTox8POmTcbbDK7nCFUPZQVI-0k7dKhBo9AojS9ez4HjZDWINBcruqvVXQwhBI5GYWSwsg0C03sm2dCnqmGIslS88E3kQUfkHcSKDPu-Y-9As7oE1xYszvy31DEr3H0ul7slHEsa5VxpYo_GRpbGBKzLFKgPrUG2jEF_JdUcNZiGZcuwRNIgF3QFNZxu6ZeMjS6U1WIbAaiuFPN9V-rPeERy3Q6ilAc5Oi-nA8j1FpuyOLxS62BUSywLVj7tCA7DL7y8DN2iAPoEiDavzdG4dbtU6opkB7btxp19hBfWPyvNzWtVCSVgF4SomxXHtNhaR6w9CeY7ZNYC_mWqAjckSkkDgsct2Vn6_od6SnQgLiDxwzv8DuEgT-N0ZsusbPGRSrRLrLcAkbKyP3iVRo1lp7gmNgi6t3lpOnXMhu_9cx1ZnYLsXwUgEBQYyid9XTsEAoTgyC001tSYJ194vEsaItkxdB5OlCBQ"
# }
### GET {{basepath}}/ with header token authroization
GET {{basepath}}/
Authorization : Bearer CfDJ8JQ6UejBIoRIkUpEJR_892d-zbl9LEcgWQiW6uF55wQzMaIo9tELg3ATO_91h3I6CFxA4uC6yNJGx2o3Mk3iSVzPF6iTZetbunzE-Yxf40apjpXEZkc_dEYMQfnpDIq8XJFclh8uWLTLk7Jq7Ne1Rg7LNK-Uh5vzqgP5bS609Viu8dV29kgtK1RfIU2N_7o4lw1X-YoX38jwyc-ArodRrJRkcMsEs0ts2L1pIRKQH8NO3x-fcmQLGJrcutKg9OBTlscx6r-WCc_bJMjGdDQgXrZEYu-XSPbgc4FAB3C3NAZFEqqwXW1NLIb_3Xa3CYqrsX2veomIXNgq3YoomZ0rMdm94gC7Z1R8LjMAWecPU9p2UB1IFIbvLMRLpmgIVHQjTaHKS42-uA0NB5TdJxaF0Gc90czUmd8PG9l5yEPgDPiQLztkk5vBm0y_HR5cgUDQdEwSQt8Av0gsmbME9atzkxeFFFTVezB52YR_SsMzbx5q_lJE-ux6SDdmykzbSwjg4ecJRPd6_G_MNMt72Pc-gTIHZC56zqyrUt_6N3RdsQTSt5_6dl42IGRMO6j6JRrk9BRpWykWLylDcLfNyfGx1QV7cyqbKIPNbOLFT2VKsA_Svz79Gb37VyiaNEppMjO2UI6CWj1DxazYWNMERiQ0Tfj1Q7HIJkFINC9fIbNPI2SjqNurAxCTIAfBqzf0Nox8hl1bcZN7OSun8-u7nhbqdg0


### refresh
POST {{basepath}}/account/refresh
Content-Type: application/json

{
  "refreshToken": "CfDJ8JQ6UejBIoRIkUpEJR_892dg_5gvwNBXBMYLYQj05RIc14gg_31KrsnOjceSSvrowYNz_kXZ2g8jdWl91ctdU3A3yy5krWnD_p-sJAUNF_OT6NTsZrhnajn7bLOtjgGQ3tbaFYq5_qEGYFXkDk9N3leqQQnyXwoa7sfIVijq_-BjK1kcg9EoyUmlQQ17ysdtw4S5AFQ8b-K8CrVCIDuUYopb5cviYcXBMBkoGz2EkY2og67F1yEFpuMbTox8POmTcbbDK7nCFUPZQVI-0k7dKhBo9AojS9ez4HjZDWINBcruqvVXQwhBI5GYWSwsg0C03sm2dCnqmGIslS88E3kQUfkHcSKDPu-Y-9As7oE1xYszvy31DEr3H0ul7slHEsa5VxpYo_GRpbGBKzLFKgPrUG2jEF_JdUcNZiGZcuwRNIgF3QFNZxu6ZeMjS6U1WIbAaiuFPN9V-rPeERy3Q6ilAc5Oi-nA8j1FpuyOLxS62BUSywLVj7tCA7DL7y8DN2iAPoEiDavzdG4dbtU6opkB7btxp19hBfWPyvNzWtVCSVgF4SomxXHtNhaR6w9CeY7ZNYC_mWqAjckSkkDgsct2Vn6_od6SnQgLiDxwzv8DuEgT-N0ZsusbPGRSrRLrLcAkbKyP3iVRo1lp7gmNgi6t3lpOnXMhu_9cx1ZnYLsXwUgEBQYyid9XTsEAoTgyC001tSYJ194vEsaItkxdB5OlCBQ"
}

### get result : {
###   "tokenType": "Bearer",
###   "accessToken": "CfDJ8JQ6UejBIoRIkUpEJR_892f0qTCKQ7Vc933AV4Gwtj28MbzZlWutb61scKn9S3siQB6gWPO18TYN9qRBb80WpKoxHrWUl-harUhOMn_L1D_p5WQxbqVhQxRg6BjRPEi_zIkGgCuL5BZd3Rr5rCYHbHSaVGH_sUqnLMMmAMJnmLhols6cIC4RleTZKK10z-is4rb2bCycD5t_4OfaSaYrqe2pLzaG6hovNaHk3l4ufnJdKNqksuXHuNqIKeOMbODp8xukPbYvRcnKWKkp4CIbZVkqPEsed4zZTSmhJIxcJ3uFt75wciGYgJua6IO00d6P1h_7m3R60tdKuPG8jQsWiPcQSkqfUoPvvo6CYju0-yhM454rVvH3_zbvAfMUt5sVGeaK12Y6cd7kZhdf8QI7XRRj6uDiWYWfyQMDTdfZpEo-u790wmUbGgM-MHzwqWJDP-cT_KTnI1VDilRYq-6L5gt9m85jf8VMWC4D4kH68dRIJ7UgbAwFCGq-wOTJ9mAKkvB7uI1P9A-rc7fvdMOgrdrb5YkDqBrSRP8uIbKfq59BxY5IH7x-psumbbcCnr9pi7XhztyAG3pZNsAsWVPt0uV70-a1V1yhfHhhgME74ll79KG1tYNuzecL54JT4nAzKQryk2keitW3nVgDJ8j2altpCKEwGyTj28ru2g9Qbnc-ou5XJgXAQRkofAVbtDMtYQ",
###   "expiresIn": 3600,
###   "refreshToken": "CfDJ8JQ6UejBIoRIkUpEJR_892dYZaodot7Ub_FXjTsnni_Mr1UtHZU3TYEXrdEDYpltxO6u9RXq5NVI8ilfkLMPt4UrGZuZJKwoFlScnFXelJx3H5PYR63TfbohEfOzwA0Gd8yzS8CN-Sr6-3_jS-MstYuHoW5RcBfOehfSW3wEN7evxt6H3S2xQkczaZ95xs-LEXFVLfPVx-m7hJA-nCRr8Zkn0nQYgQGCP-ubcQY9OnklQvQnE4UxZX0J1myxy-kLxtotgi8TcxMp0AINRcHU7lJ1GK0m-NqD9w1bVb-mQweJpcvV4n5i0aV8DXwVX5H5SLq0E0YoEUDXbWhKA3N0CpzmkCoKWabTHZcq1hpIEvfKOI0D-fzX0j7ToLIS-aTzb8jy46jGsdYFznxUlbCblssea7vI_R0dJ2Spp-uzlvBsn0AXfbVJmkvJ6jKsOR5d9gHfF79KWqrdJR22EsQ3tydtHVMnH8es4d4_xjanCLLSsLNaKkF0ZhazdhKMKyz2DGGoC_m9n0mc27cAEPAChx4FzGmqRp1bN2vMxW4TMkWsNM00yZGuPKhKLYYzkHhNiKeSIMpm8XISRXpm5HNBnxasN9XIDr4o_t0G82GsdWjoA1AD64-39OQzNNnf14-QLw8VOeIvQpf7IKhC3nf9fxo3W16um76JmcEGR-TJn4F52nQdUB9heNOmijE1Vn61vw"
### }

